
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://123.57.235.72:3306/read?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
#  data:
#    solr:
#      host: http://localhost:8983/solr
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

mybatis:
  mapper-locations: classpath:org.lanqiao.mapper/*Mapper.xml
  type-aliases-package: org.lanqiao.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        mapper: debug

#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql